/**
 * @file http_parser.h
 * @brief Definition of the HTTP request/response parser wrapper.
 *
 * This file defines the classes that will be used to parse incoming
 * HTTP request data. It acts as a wrapper around the underlying
 * state machine parser (e.g., generated by Ragel or http-parser).
 */
#ifndef __SYLAR_HTTP_PARSER_H__
#define __SYLAR_HTTP_PARSER_H__

#include "sylar/http/http.h"

namespace sylar {
namespace http {

class HttpRequestParser {
public:
    typedef std::shared_ptr<HttpRequestParser> ptr;
    HttpRequestParser();
    // ... parser methods
};

class HttpResponseParser {
public:
    typedef std::shared_ptr<HttpResponseParser> ptr;
    HttpResponseParser();
    // ... parser methods
};

}
}

#endif
