/**
 * @file http_parser.cpp
 * @brief Implementation of the HTTP parser wrapper.
 *
 * This file contains the implementation of the parser wrapper classes.
 * It would typically include the C file generated by Ragel and bridge
 * its events to the HttpRequest/HttpResponse objects.
 */
#include "sylar/http/http_parser.h"
#include "sylar/log.h"

// #include "http11_parser.c" // Ragel output
// #include "httpclient_parser.c" // Ragel output

namespace sylar {
namespace http {

HttpRequestParser::HttpRequestParser() {
    // Constructor
}

HttpResponseParser::HttpResponseParser() {
    // Constructor
}

}
}
